---
language: bash
services: docker

env:
- VERSION=2.2.1.0
- VERSION=2.3.2.0 LATEST_VERSION=true

before_script:
- env | sort
- export IMAGE="quay.io/antonu17/ansible-ci"

script:
- ci/scripts/build.sh
