---
language: bash
services: docker
env:
- VERSION: 2.2.1.0
- VERSION: 2.3.2.0

before_script:
- env | sort
- cd ${VERSION}
- IMAGE="quay.io/antonu17/ansible-ci"

script:
- [ $TRAVIS_PULL_REQUEST = 1 ] && ci/scripts/build-pr.sh
