# Nothing 
source 'https://rubygems.org'

group :production do
  gem 'test-kitchen'
  gem 'kitchen-ec2'
  gem 'kitchen-ansiblepush'
  gem 'kitchen-docker'
  gem 'kitchen-vagrant'
  gem 'kitchen-goss'
  gem 'kitchen-localhost'
  gem 'net-ssh', '~> 2.0'
  gem 'faraday'
  gem "jmespath"
  gem "net-scp"
  gem "aws-sdk-resources"  
end
  